name: Linting
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ruff lint
        uses: astral-sh/ruff-action@v3
        with:
          args: "check --output-format=github"
      - name: Ruff format check
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"
